export const FETCH_ATHLETE = 'fetch_athlete'
export const IMPORT_ACTIVITIES_FROM_STRAVA_TO_DB = 'import_activities_from_strava_to_db'
export const STRAVA_DATA_LOADING = 'strava_data_loading'
export const FETCH_RIDES = 'fetch_rides'
export const FETCH_PROGRESSION = 'fetch_progression'
export const FETCH_BIKE_USAGE = 'fetch_bike_usage'
